package com.slinky.wordcheat.model;

/**
 * Represents a move suggestion generated by a WordFinder object.
 * 
 * <p>
 * A {@code Move} encapsulates a candidate word along with its associated
 * score, the starting coordinates (row and column) for its placement on the
 * game board, and a flag indicating whether the word is placed vertically or
 * horizontally. This record is used for presenting potential moves or valid
 * words to the user.
 * </p>
 *
 * @param word  the suggested word.
 * @param score the score associated with the suggested word.
 * @param row   the starting row index (zero-based) where the word is placed.
 * @param col   the starting column index (zero-based) where the word is placed.
 * @param verticallyPlaced {@code true} if the word is placed vertically;
 *                         {@code false} if it is placed horizontally.
 * @see    WordFinder
 * @author Kheagen Haskins
 */
public record Move(String word, int score, int row, int col, boolean verticallyPlaced)
        implements Comparable<Move> {

    // ================================[ Static ]================================ \\
    /**
     * The template used to format the string representation of a
     * {@code Move}.
     * 
     * <p>
     * The template follows the format:
     * <pre>
     *     "[%s] [%3d] %s at (%d, %d)"
     * </pre> where:
     * <ul>
     *   <li>The first placeholder is replaced with "V" if the move is
     *       vertical or "H" if horizontal.</li>
     *   <li>The second placeholder displays the score in a field width of 3.</li>
     *   <li>The third placeholder is replaced with the suggested word.</li>
     *   <li>The fourth and fifth placeholders represent the row and column
     *       indices, respectively.</li>
     * </ul>
     * </p>
     */
    private static final String TO_STRING_TEMPLATE = "[%s] [%3d] %s at (%d, %d)";

    // =============================[ API Methods ]============================== \\
    /**
     * Returns a formatted string representation of this {@code Move}.
     * 
     * <p>
     * The format of the returned string is defined by
     * {@code TO_STRING_TEMPLATE} and includes:
     * <ul>
     *   <li>A marker indicating whether the move is vertical ("V") or
     *       horizontal ("H").</li>
     *   <li>The score associated with the word, right-aligned in a field of width
     *       3.</li>
     *   <li>The suggested word.</li>
     *   <li>The starting position (row and column) of the word on the game
     *       board.</li>
     * </ul>
     * </p>
     *
     * @return a formatted string representation of this move.
     */
    @Override
    public String toString() {
        return TO_STRING_TEMPLATE.formatted((verticallyPlaced ? "V" : "H"), score, word, row, col);
    }

    /**
     * Compares this {@code Move} with the specified {@code Move} for order.
     * The comparison is based on the score in descending order.
     *
     * @param other the other move to be compared.
     * @return a negative integer, zero, or a positive integer as this move's score
     *         is greater than, equal to, or less than the specified move's score.
     */
    @Override
    public int compareTo(Move other) {
        return Integer.compare(other.score, this.score);
    }
    
}